#!/bin/bash
#!/bin/sh
#######################################
# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################
#  Written by Anoop Singh from https://www.hostingshades.com/

#COLORS
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Default Credentials
ADMIN_DEF="admin"               # Defualt suitecrm admin user name
ADMINPASS_DEF="admin@12345"     # Defualt suitecrm pass name
date=`date`
Suiteversion="8.2.0"
prefix="tenant_"
u="_"
################################

#.1....###### MYSQL SHOW

#.2....###### READING DATA FROM USER ######
echo -en "$BWhite \n Please Enter SuiteCRM Company Name                        :$BGreen"
read COMPANY

echo -en "$BWhite \n Please Enter SuiteCRM Domain Name Or DNS Name/Entry       :$BGreen"
read DOMAIN_NAME

while true; do
 
echo -en "$BWhite Do You Want to Print MySQL Databases ? Yes or No: $BGreen"
read showdatabases
 
      case $showdatabases in
            [yY][eE][sS]|[yY])
echo -e "$BCyan-----------------------------Printing Databases ------------------------------------$Color_Off"
sleep 2   
mysql -u root -e "SHOW DATABASES"                       
             break;;               
        
            
            [nN][oO]|[nN]) echo -e "$Color_Off"
             break;;
    
            *) echo -e "$BYellow Wrong Input ! Please Answer Yes or No $Color_Off" 
      esac 
done

# read -e -p "$(echo -e $BWhite Please Enter Databases User $Color_Off) : " $prefixDB_USER
echo -en "$BWhite Please Enter SuiteCRM Databases Name                      :$BYellow"$prefix
 read DB_NAME

echo -en "$BWhite Please Enter SuiteCRM Databases Username                  :$BYellow"$prefix
read DB_USER

echo -en "$BWhite Please Enter SuiteCRM Databases Password                  :$BGreen"
read DB_PASSWD

echo -en "$BWhite Please Enter SuiteCRM Admin Name           $BYellow(default $ADMIN_DEF):$BGreen"
read ADMIN
ADMIN="${ADMIN:-$ADMIN_DEF}"

echo -en "$BWhite Please Enter SuiteCRM Admin Password$BYellow (default $ADMINPASS_DEF):$BGreen"
read ADMINPASS
ADMINPASS="${ADMINPASS:-$ADMINPASS_DEF}"
echo -e "$Color_Off"

echo -e "$BCyan------------------------------- SUMMARY OF INSTALLATION ---------------------------------$Color_Off"

echo -en "$BGreen \n SuiteCRM Version            :$BYellow $Suiteversion $Color_Off"
echo -en "$BGreen \n Company Name                :$BYellow $COMPANY $Color_Off"
echo -en "$BGreen \n SuiteCRM DNS Name           :$BYellow $COMPANY.$DOMAIN_NAME $Color_Off"
# echo -en "$BGreen \n SuiteCRM Domain Name        :$BYellow $DOMAIN_NAME $Color_Off"
echo -en "$BGreen \n SuiteCRM Databases Name     :$BYellow $prefix$DB_NAME $Color_Off"
echo -en "$BGreen \n SuiteCRM Databases Username :$BYellow $prefix$DB_USER $Color_Off"
echo -en "$BGreen \n SuiteCRM Databases Password :$BYellow $DB_PASSWD $Color_Off"
echo -en "$BGreen \n SuiteCRM Admin Name         :$BYellow $ADMIN $Color_Off"
echo -e "$BGreen \n SuiteCRM Admin Password     :$BYellow $ADMINPASS $Color_Off"


#.3..##### Installing SuiteCRM.....
while true; 
do
echo -en "$BWhite \n Do You Want Install SuiteCRM  ..... Y/N: $BGreen"
read suite

case $suite in
        y|Y|yes|Yes|YES) 
      
echo -e "$BCyan----------------------------- Creating Vhost for The Domain -----------------------------$Color_Off"        
sleep 2

FILE=/etc/httpd/conf.d/$DOMAIN_NAME.conf     
if [ -f $FILE ]; then
   echo -e "$BRed File $DOMAIN_NAME.conf already exists. Unable to create Vhost for the Domain $Color_Off" 1>&2 
   
   break 1
else
   echo "<VirtualHost *:80>
    ServerAdmin admin@$DOMAIN_NAME
    DocumentRoot "/var/www/html/$DOMAIN_NAME/public"
    DirectoryIndex index.php index.php4 index.php5 index.htm index.html
    ServerName $DOMAIN_NAME
    ErrorLog "/var/log/httpd/$DOMAIN_NAME.error_log"
    CustomLog "/var/log/httpd/$DOMAIN_NAME.access_log" common

     <Directory /var/www/html/$DOMAIN_NAME/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
     </Directory>

    </VirtualHost>
    " >/etc/httpd/conf.d/$DOMAIN_NAME.conf
fi


#.4..################## Create Databases and User ##################################

echo -e "$BCyan------------------------ Creating Databases and User for SuiteCRM -----------------------$Color_Off"
sleep 2

 RESULT=`mysql -u root -e "SHOW DATABASES" | grep $DB_NAME`
 if [ "$RESULT" == "$DB_NAME" ]; then
    echo -e "$BYellow The Database Named $BRed $DB_NAME $Color_Off $BYellow already exists $Color_Off"
    echo -e "$BWhite We Suggest Trying the New Database Name $Color_Off"
    exit 1
  else
    echo -e "$BYellow The Database Name $prefix$DB_NAME Has Been Created Successfully! $Color_Off"
    mysql -u root  -e "CREATE DATABASE $prefix$DB_NAME";
    mysql -u root  -e "CREATE USER '$prefix$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWD'";
    mysql -u root  -e "GRANT ALL PRIVILEGES ON $prefix$DB_NAME.* TO '$prefix$DB_USER'@'localhost'";
    mysql -u root  -e "FLUSH PRIVILEGES";
 fi


echo -e "$BCyan---------------------------Installing SuiteCRM for $DOMAIN_NAME -------------------------$Color_Off"
sleep 2   
    cd /var/www/html
    mkdir $DOMAIN_NAME && cd $DOMAIN_NAME
    wget -qc https://suitecrm.com/download/128/suite82/561615/suitecrm-8-2-0-zip.zip
    unzip suitecrm-8-2-0-zip.zip

    find . -type d -not -perm 2755 -exec chmod 2755 {} \;
    find . -type f -not -perm 0644 -exec chmod 0644 {} \;
    find . ! -user apache -exec chown apache:apache {} \;
    chmod +x bin/console
    service httpd restart
    rm -rvf suitecrm-8-2-0-zip.zip

   

    ./bin/console suitecrm:app:install -u "$ADMIN" -p "$ADMINPASS" -U "$prefix$DB_USER" -P "$DB_PASSWD" -H "localhost" -N "$prefix$DB_NAME" -S "https://$DOMAIN_NAME" -d "yes"

    find . -type d -not -perm 2755 -exec chmod 2755 {} \;
    find . -type f -not -perm 0644 -exec chmod 0644 {} \;
    find . ! -user apache -exec chown apache:apache {} \;
    sudo chown -R apache:apache /var/www/html

echo -en "$BGreen \n SuiteCRM Link      : $BYellow http://$DOMAIN_NAME $Color_Off"
echo -en "$BGreen \n SuiteCRM Admin User: $BYellow $ADMIN $Color_Off"
echo -e "$BGreen \n SuiteCRM Admin Pass : $BYellow $ADMINPASS $Color_Off"

echo -e "$BGreen \n SuiteCRM And Databases Details Have been Stored In $BYellow /var/www/html/$DOMAIN_NAME.txt $Color_Off"

echo "Creaction Date is: $date
SuiteCRM_Admin_Details:
SuiteCRM Link:http://$DOMAIN_NAME
SuiteCRM Admin User:$ADMIN 
SuiteCRM Admin Pass:$ADMINPASS

DataBases_Details:
Databases Name:  $DB_NAME
Database UserName:$DB_USER
Database Password:$DB_PASSWD
" >/var/www/html/$DOMAIN_NAME.txt
sudo chown -R apache:apache /var/www/html

    break;;



        n|N|no|No|NO) echo -e "$Color_Off"
        break;;
 
        *) echo -e "$BYellow Wrong Input ! Please Answer Yes or No $Color_Off" 
 
esac
done

#.5.################# Install Let’s Encrypt with Apache ###########################
 
while true; do
 DIR=/etc/letsencrypt/live/$DOMAIN_NAME
 echo -en "$BWhite Do you want to install SSL ? Yes or No ...: $BGreen"
 read ssl
 
      case $ssl in
            [yY][eE][sS]|[yY])
echo -e "$BCyan------------------------ Installing Let's Encrypt for $DOMAIN_NAME ----------------------$Color_Off"
sleep 2                           
                            certbot --apache -d $DOMAIN_NAME
                            
                            
                              if [ -d $DIR ]; then
                              echo -e "$BGreen SSL Installation Successfully Completed $Color_Off"
                              break 1
                              
                              else
                              echo -e "$BRed  SSL installation has been failed $Color_Off"
                              
                              fi
                              
                           echo -e "$Color_Off" ;;
            
            [nN][oO]|[nN]) echo -e "$Color_Off"
             break;;
    
            *) echo -e "$BYellow Wrong Input ! Please Answer Yes or No $Color_Off" 

      esac 
done

########################  END #####################################################

