#!/bin/bash
#!/bin/sh
#######################################
# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################
#  Written by Anoop Singh from http://hostingshades.com/

#COLORS
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White


################################
while true; 
do
echo -en "$BWhite Do You Want Install SuiteCRM  ..... Y/N: $BGreen"
read suite

case $suite in
        y|Y|yes|Yes|YES) # Create Vhost for Domain
        echo -en "$BWhite Please Enter Domain Name Or DNS Name/Entry:$BGreen"
        read DOMAIN_NAME
        
echo -e "$BCyan ========================================================================="
echo -e "$BCyan             Creating Vhost for The Domain...                             "
echo -e "$BCyan ========================================================================="
echo -e "$Color_Off"

sleep 2

FILE=/etc/httpd/conf.d/$DOMAIN_NAME.conf     
if [ -f $FILE ]; then
   echo -e "$BRed File $DOMAIN_NAME.conf already exists. Unable to create Vhost for the Domain $Color_Off" 1>&2 
   
   break 1
else
   echo "<VirtualHost *:80>
    ServerAdmin admin@$DOMAIN_NAME
    DocumentRoot "/var/www/html/$DOMAIN_NAME/public"
    DirectoryIndex index.php index.php4 index.php5 index.htm index.html
    ServerName $DOMAIN_NAME
    ErrorLog "/var/log/httpd/$DOMAIN_NAME.error_log"
    CustomLog "/var/log/httpd/$DOMAIN_NAME.access_log" common

     <Directory /var/www/html/$DOMAIN_NAME/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
     </Directory>

    </VirtualHost>
    " >/etc/httpd/conf.d/$DOMAIN_NAME.conf
fi

################################################################################
################### Create Databases and User ##################################
################################################################################
echo -e "$BCyan  ========================================================================="
echo -e "$BCyan           Creating Databases and User for SuiteCRM...                     "
echo -e "$BCyan  ========================================================================="
echo -e "$Color_Off"
sleep 1

mysql -u root -e "SHOW DATABASES"

echo -en "$BWhite Please Enter Databases Name :$BGreen"
read DB_NAME


echo -en "$BWhite Please Enter Databases Username :$BGreen"
read DB_USER


echo -en "$BWhite Please Enter Databases Password $BYellow :$BGreen"
read DB_PASSWD


echo -e "$Color_Off"

 RESULT=`mysql -u root -e "SHOW DATABASES" | grep $DB_NAME`
 if [ "$RESULT" == "$DB_NAME" ]; then
    echo -e "$BYellow The Database Named $BRed $DB_NAME $Color_Off $BYellow already exists $Color_Off"
    echo -e "$BWhite We Suggest Trying the New Database Name $Color_Off"
    exit 1
  else
    echo -e "$BYellow The Database Name $DB_NAME Has Been Created Successfully! $Color_Off"
    mysql -u root  -e "CREATE DATABASE $DB_NAME";
    mysql -u root  -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWD'";
    mysql -u root  -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'";
    mysql -u root  -e "FLUSH PRIVILEGES";
 fi

################################################################################
################################Install SuiteCRM ###############################
################################################################################

    echo -e "$BCyan  ========================================================================="
    echo -e "$BCyan         Installing SuiteCRM for $DOMAIN_NAME .....                         "
    echo -e "$BCyan  ========================================================================="
    echo -e "$Color_Off"


    cd /var/www/html
    mkdir $DOMAIN_NAME && cd $DOMAIN_NAME
    wget -qc https://suitecrm.com/download/128/suite82/561615/suitecrm-8-2-0-zip.zip
    unzip suitecrm-8-2-0-zip.zip

    find . -type d -not -perm 2755 -exec chmod 2755 {} \;
    find . -type f -not -perm 0644 -exec chmod 0644 {} \;
    find . ! -user apache -exec chown apache:apache {} \;
    chmod +x bin/console
    service httpd restart


    echo -en "$BWhite Please Enter SuiteCRM Admin Name :$BGreen"
    read ADMIN
    

    echo -en "$BWhite Please Enter SuiteCRM Password :$BGreen"
    read ADMINPASS
    
    echo -e "$Color_Off"

    ./bin/console suitecrm:app:install -u "$ADMIN" -p "$ADMINPASS" -U "$DB_USER" -P "$DB_PASSWD" -H "localhost" -N "$DB_NAME" -S "https://$DOMAIN_NAME" -d "yes"

    find . -type d -not -perm 2755 -exec chmod 2755 {} \;
    find . -type f -not -perm 0644 -exec chmod 0644 {} \;
    find . ! -user apache -exec chown apache:apache {} \;
    sudo chown -R apache:apache /var/www/html

    echo -en "$BGreen \n SuiteCRM Link: $BYellow http://$DOMAIN_NAME $Color_Off"
    echo -en "$BGreen \n SuiteCRM Admin User: $BYellow $ADMIN $Color_Off"
    echo -e "$BGreen \n SuiteCRM Admin Pass: $BYellow $ADMINPASS $Color_Off"
    echo -e "$BGreen \n SuiteCRM And Databases Details Have been Stored In $BYellow /var/www/html/$DOMAIN_NAME.csv $Color_Off"
echo "SuiteCRM_Admin_Details:
SuiteCRM Link:http://$DOMAIN_NAME
SuiteCRM Admin User:$ADMIN 
SuiteCRM Admin Pass:$ADMINPASS

DataBases_Details:
Databases Name:  $DB_NAME
Database UserName:$DB_USER
Database Password:$DB_PASSWD
" >/var/www/html/$DOMAIN_NAME.csv
sudo chown -R apache:apache /var/www/html

    break;;



        n|N|no|No|NO) echo -e "$Color_Off"
        exit;;
 
        *) echo -e "$BYellow Wrong Input ! Please Answer Yes or No $Color_Off" 
 
esac
done


################################################################################
################## Install Let’s Encrypt with Apache ###########################
################################################################################
while true; do
 echo -en "$BWhite Do you want install SSL ? Yes or No ..... : $BGreen"
 read ssl

    case $ssl in
            [yY][eE][sS]|[yY])
                            echo -e "$BCyan                         ========================================================================="
                            echo -e "$BCyan                                   Installing Let's Encrypt for $DOMAIN_NAME ....."
                            echo -e "$BCyan                         ========================================================================="
                            echo -e "$Color_Off"
                            yum install epel-release -y
                            yum install certbot python2-certbot-apache mod_ssl -y
                            certbot --apache -d $DOMAIN_NAME
                            #echo -e "$Color_Off" ;;
                            break;;
            
            [nN][oO]|[nN]) echo -e "$Color_Off"
             break;;
    
            *) echo -e "$BYellow Wrong Input ! Please Answer Yes or No $Color_Off" 
            
    esac
done


########################  END #####################################################
